name: Manual workflow

on:
  push:

jobs:

  e2e-test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1

      - name: Install
        run: npm install

      - name: Test
        run: npm run e2e:test
